- hosts: localhost
  tasks:
    - name: removendo imagem
      docker_container:
        name: webdeploy
        state: absent
    - name: removendo
      docker_image:
        name: thiagolangoni/jenkinsbuildimagedocker
        state: absent
    - name: run container
      docker_container:
        name: webdeploy
        image: thiagolangoni/jenkinsbuildimagedocker:latest
        ports:
         - "5000:5000"
  
